### ISSUE TITLE
dependency "nikic/php-parser" can be a dev-dependency, or?

### ISSUE THREAD

**Issue by voku** [shipmonk-rnd/phpstan-rules#257]
I skiped the installation of "nikic/php-parser" and it's still working because phpstan/phpstan (the phar file) has his dependency already included, or?

same as here: https://github.com/sidz/phpstan-rules/issues/25

**Comment by janedbal** [comment]
Please upgrade, this has been [fixed in 2.11.3](https://github.com/shipmonk-rnd/phpstan-rules/releases/tag/2.11.3)
