### ISSUE TITLE
Current release broken ?

### ISSUE THREAD

**Issue by ilazaridis** [shipmonk-rnd/phpstan-rules#47]
I need to remove both `ForbidMethodCallOnMixedRule` and `ForbidFetchOnMixedRule` from `neon.rules` in order to make it work. 

I think I already stumbled upon a commit that solves this.

JFYI :)

Thank you & great work!

**Comment by ilazaridis** [comment]
I will write a proper report, closing for now.

**Comment by janedbal** [comment]
Latest version you see in readme is not yet tagged, but if you use dev-master, you should be able to do it as desribed there. Feel free to report any problems with it. I plan to tag it soon as 2.0.0

**Comment by ilazaridis** [comment]
yeah, sorry for the noise and thanks for the reply.
