### ISSUE TITLE
Custom allowComparingOnlyComparableTypes

### ISSUE THREAD

**Issue by sylfabre** [shipmonk-rnd/phpstan-rules#85]
Hello

Thank you for this great set of phpstan rules.

We developed http://github.com/assoconnect/php-date which supports comparison.
`allowComparingOnlyComparableTypes` is powerful but isn't customizable so I can't enable it.

Could you please make this rule accept a whitelist of function which supports comparison?

Thank you!

**Comment by janedbal** [comment]
I believe comparing objects in PHP (>,<,<=,>=,<=>) is too magical and should be avoided. You cannot easily overload operators and default PHP implementation compares properties based on their definition order which can easily break by some refactoring of the class. [See example](https://3v4l.org/JF0VX). Therefore I do not want to support such feature. Typical implementation for such objects in PHP is to add methods for comparison (isAfter, isBefore, ...), see e.g. [brick/datetime](https://github.com/brick/date-time/blob/master/src/Instant.php) implementation.

You can always disable that rule and copy-paste it to your codebase with the changes you need.

**Comment by sylfabre** [comment]
Hello @janedbal 

Thank you for the example, I wasn't aware of it!

I'm curious: why is comparison of `DateTimeInterface` allowed then?

**Comment by janedbal** [comment]
Because it is PHP internal class that has special implementation for it in PHP core.

**Comment by sylfabre** [comment]
Makes sense, thank you for the explanation 👍
