### ISSUE TITLE
EnforceReadonlyPublicPropertyRule reports false-positive with PHP 7.4

### ISSUE THREAD

**Issue by sylfabre** [shipmonk-rnd/phpstan-rules#86]
Hello

Read-only properties are only available with PHP 8.1+

So `EnforceReadonlyPublicPropertyRule` reports false-positive with public properties with PHP 7.4
Would you accept a PR to fix this?

**Comment by janedbal** [comment]
Fixed in https://github.com/shipmonk-rnd/phpstan-rules/pull/87, sorry for so basic error. I'll check that other issue you reported and possibly tag the fixed version in upcoming days.

**Comment by janedbal** [comment]
[Tagged as 2.3.1](https://github.com/shipmonk-rnd/phpstan-rules/releases/tag/2.3.1)
